#!/bin/bash

set -e # If any command fails, stop execution of the hook with that error

. hooks/proj.cfg

juju-log "Entered the $PROJ_NAME charm install hook."

apt-get update
apt-get -y --no-install-recommends install openjdk-7-jdk
apt-get -y install curl

# some common tools
mkdir /opt/tools
curl http://apache.openmirror.de/maven/maven-3/3.2.1/binaries/apache-maven-3.2.1-bin.tar.gz | tar xz -C /opt/tools
curl http://www.apache.org/dist/ant/binaries/apache-ant-1.9.3-bin.tar.bz2 | tar xj -C /opt/tools
for i in /opt/tools/*/bin/*; do ln -s $i /usr/bin ; done

juju-log "Java, Git and Maven successfully installed."

rm -rf "$PROJ_DIR"
git clone https://github.com/instauth/$PROJ_NAME.git "$PROJ_DIR"

juju-log "$PROJ_NAME successfully cloned."

/usr/bin/mvn -Dmaven.test.skip=true -f $PROJ_DIR/pom.xml install

juju-log "$PROJ_NAME successfully installed."

exit 0
