#!/bin/bash

set -e # If any command fails, stop execution of the hook with that error
juju-log "I am in $(pwd)"

. hooks/proj.cfg

juju-log "Entered the $PROJ_NAME charm install hook."

apt-get install -y software-properties-common
add-apt-repository -y ppa:webupd8team/java
apt-get update
echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections
apt-get install -y oracle-java7-installer

apt-get install -y git
apt-get install -y maven

juju-log "Java, Git and Maven successfully installed."

rm -rf $PROJ_DIR
git clone https://github.com/instauth/${PROJ_DIR}.git

juju-log "$PROJ_DIR successfully cloned."

/usr/bin/mvn -Dmaven.test.skip=true -f $PROJ_DIR/pom.xml install

juju-log "$PROJ_NAME successfully installed."

exit 0
