#!/bin/bash

set -e # If any command fails, stop execution of the hook with that error

. hooks/proj.cfg

juju-log "Entered the $PROJ_NAME charm start hook."

juju-log "Opening port $PORT for $PROJ_NAME"
open-port $PORT

"$PROJ_DIR/start" &
disown

juju-log "$PROJ_NAME starting..."

