#!/bin/bash

set -e # If any command fails, stop execution of the hook with that error

. hooks/proj.cfg

juju-log "Entered the $PROJ_NAME charm stop hook."

juju-log "$PROJ_NAME stopping..."

killall java

rm -f .lock && juju-log "Removed lockfile - waiting 30 seconds." && sleep 30
